import { createContext, useContext, useState } from 'react'

// ─── PT-BR ────────────────────────────────────────────────────────────────────
const PT = {
  flag: '🇧🇷', name: 'Português', short: 'PT',
  nav: { home: 'Início', company: 'A Empresa', services: 'Serviços', fleet: 'Nossa Frota', esg: 'ESG', certifications: 'Certificações', blog: 'Blog', report: 'Denúncia', careers: 'Trabalhe Conosco', quote: 'Orçamento' },
  serviceItems: ['Movimentação Horizontal e Vertical de Cargas', 'Movimentação de Cargas', 'Locação de Equipamentos', 'Linha Amarela (Retroescavadeira)', 'Transporte de Cargas Especiais'],
  home: {
    heroTag: 'Mais de 25 anos movendo o Brasil',
    heroSub: 'Soluções de alta performance em movimentação de cargas, transporte pesado, remoção industrial e locação de equipamentos.',
    heroBtnServices: 'Nossos Serviços', heroBtnQuote: 'Fazer Orçamento',
    statLabel1: 'Anos de tradição', statLabel2: 'Projetos executados', statLabel3: 'Compromisso operacional', statSub4: '9001 Certificado',
    svcEyebrow: 'O que fazemos', svcTitle: 'Soluções para qualquer desafio logístico', svcSub: 'Equipamentos modernos e equipes certificadas para garantir a segurança da sua carga.',
    svcMore: 'Ver mais', svcBtn: 'Ver todos os serviços',
    services: [
      { title: 'Movimentação Horizontal e Vertical de Cargas', desc: 'Içamento e posicionamento de equipamentos e estruturas pesadas com rigging de alta complexidade, operadores certificados NR-11 e memorial de cálculo assinado por engenheiro.' },
      { title: 'Movimentação de Cargas', desc: 'Planejamento e execução de mudanças de layout fabril, posicionamento de máquinas e desmontagem de equipamentos industriais com a menor paralisação possível na produção.' },
      { title: 'Locação de Equipamentos', desc: 'Frota moderna e diversificada disponível em contratos de curto e longo prazo — guindastes, caminhão-guindauto e linha amarela — com manutenção preventiva e suporte 24/7.' },
      { title: 'Linha Amarela (Retroescavadeira)', desc: 'Retroescavadeiras, pás carregadeiras e escavadeiras hidráulicas para terraplanagem, escavação e movimentação de solo, com operadores certificados e documentação vigente.' },
      { title: 'Transporte de Cargas Especiais', desc: 'Transporte rodoviário de cargas superdimensionadas com carretas especiais, caminhão-guindauto, escolta credenciada, licenças DNIT/DER e rota planejada por engenheiro.' },
    ],
    splitEyebrow: 'Nossa história', splitTitle: '25 anos construindo com confiança',
    splitBody1: 'Fundamos o Grupo Maxpesa com o propósito de transformar a logística pesada no Brasil — com segurança, precisão e comprometimento em cada operação.',
    splitBody2: 'Hoje somos referência nacional, com frota própria moderna, engenharia proprietária e equipes certificadas.',
    splitBtnCompany: 'Conheça a empresa', splitBtnContact: 'Falar com a equipe',
    whyEyebrow: 'Nossos diferenciais', whyTitle: 'Por que escolher a Maxpesa', whySub: 'Comprometidos com segurança, precisão e resultado em cada operação.',
    why: [
      { title: 'Segurança acima de tudo', desc: 'Programa NR-11 rigoroso, inspeções periódicas e treinamento contínuo.' },
      { title: 'Engenharia proprietária', desc: 'Plano de rigging e memorial de cálculo entregues antes de cada mobilização.' },
      { title: 'Disponibilidade 24/7', desc: 'Frota com manutenção preventiva e suporte disponível para emergências.' },
    ],
    ctaEyebrow: 'Fale com um especialista', ctaTitle: 'Pronto para o seu próximo projeto?', ctaSub: 'Nossa equipe responde com proposta técnica em até 2 horas.',
    ctaBtnQuote: 'Solicitar orçamento', ctaBtnWpp: 'WhatsApp',
    clientsEyebrow: 'Quem confia na Maxpesa', clientsTitle: 'Parceiros que constroem o Brasil conosco',
  },
  empresa: {
    heroEyebrow: 'Nossa História', heroSub: 'Fundados para transformar a logística pesada no Brasil — com segurança, precisão e comprometimento.', heroCrumb: 'A Empresa',
    aboutEyebrow: 'Quem somos',
    aboutLead: 'O Grupo Maxpesa nasceu com o propósito de transformar a logística pesada no Brasil — entregando soluções de engenharia de rigging com segurança e precisão.',
    aboutBody: 'Atuamos de forma estratégica com soluções integradas para indústrias, comércio e infraestrutura. Nosso compromisso inegociável com a segurança nos permite enfrentar os maiores desafios logísticos com precisão milimétrica.',
    statLabel1: 'Anos de tradição', statLabel2: 'Projetos executados', statLabel3: 'Compromisso',
    tlEyebrow: 'Nossa trajetória', tlBtn: 'Fale com nossa equipe',
    timeline: [
      { year: '1998', title: 'Fundação do Grupo Maxpesa', desc: 'Início das operações no Rio de Janeiro com foco em movimentação vertical e locação de guindastes.' },
      { year: '2003', title: 'Expansão da frota e novos segmentos', desc: 'Incorporação de caminhões-guindauto e carretas especiais, abrindo o segmento de cargas superdimensionadas.' },
      { year: '2009', title: 'Certificação ISO 9001', desc: 'Reconhecimento formal do sistema de gestão da qualidade, consolidando processos de classe mundial.' },
      { year: '2014', title: 'Grandes projetos de infraestrutura', desc: 'Participação em obras de relevância nacional, incluindo projetos petroquímicos e de geração de energia.' },
      { year: '2023', title: '25 anos — novo patamar', desc: 'Renovação da frota, investimento em tecnologia de rigging e expansão para novos estados brasileiros.' },
    ],
    mvvEyebrow: 'Nossa essência', mvvTitle: 'Missão, Visão e Valores', mvvSub: 'Os princípios fundamentais que orientam cada decisão e definem quem somos.',
    mvv: [
      { label: 'Missão', items: ['Produtos e serviços de alta qualidade', 'Ambiente de trabalho positivo e colaborativo', 'Impacto positivo em clientes e colaboradores', 'Responsabilidade com a comunidade'] },
      { label: 'Visão', items: ['Empresa de referência no segmento', 'Soluções inovadoras e tecnológicas', 'Princípios éticos em todas as decisões', 'Responsabilidade ambiental e crescimento sustentável'] },
      { label: 'Valores', items: ['Ética e honestidade', 'Integridade e disciplina', 'Transparência', 'Responsabilidade social', 'Obsessão pela segurança'] },
    ],
    opEyebrow: 'Como operamos', opTitle: 'Pilares operacionais', opSub: 'Os alicerces práticos que orientam cada operação, equipe e entrega do Grupo Maxpesa.',
    values: [
      { title: 'Segurança', desc: 'A segurança de colaboradores e clientes é inegociável. Cada operação começa e termina com protocolos rigorosos de NR-11.' },
      { title: 'Excelência técnica', desc: 'Engenharia proprietária, equipamentos certificados e operadores com formação contínua garantem o padrão mais alto.' },
      { title: 'Comprometimento', desc: 'Prazo, escopo e qualidade são compromissos assumidos e honrados. Nossa reputação é 25 anos de palavra cumprida.' },
      { title: 'Inovação', desc: 'Investimento constante em novas tecnologias e metodologias para oferecer sempre a melhor solução.' },
      { title: 'Relacionamento', desc: 'Parcerias de longo prazo baseadas em confiança, transparência e resultados são nossa maior conquista.' },
      { title: 'Responsabilidade', desc: 'Valorizamos nossas equipes, respeitamos comunidades e operamos com consciência ambiental.' },
    ],
    locEyebrow: 'Onde estamos', locTitle: 'Nossa sede', locSub: 'Localizada em Duque de Caxias — RJ, a sede do Grupo Maxpesa serve todo o território nacional.', locBadge: 'Sede', locMapTitle: 'Sede Grupo Maxpesa',
  },
  servicos: {
    heroEyebrow: 'Portfólio completo', heroSub: 'Equipamentos certificados e equipes especializadas para cada tipo de desafio logístico.', heroCrumb: 'Serviços',
    btn: 'Solicitar cotação', specialEyebrow: 'Não encontrou o que precisa?', specialBtn: 'Falar com um especialista',
    services: [
      { num: '01', title: 'Movimentação Horizontal e Vertical de Cargas', intro: 'Içamento, posicionamento e transferência de equipamentos e estruturas pesadas com rigging de alta complexidade.', body: 'Nossa equipe elabora estudos de rigging personalizados com memorial de cálculo e RRT assinado por engenheiro responsável — garantindo segurança absoluta em cada operação.', feats: ['Guindastes telescópicos de 25 t a 1.200 t', 'Operadores certificados NR-11', 'Memorial de cálculo e RRT assinado', 'Içamentos em espaços confinados', 'Cobertura RCTR-C inclusa'] },
      { num: '02', title: 'Movimentação de Cargas', intro: 'Planejamento e execução de mudanças de layout fabril, posicionamento de máquinas e desmontagem de equipamentos industriais.', body: 'Nossa engenharia elabora cronograma de intervenção garantindo a menor paralisação possível na linha de produção.', feats: ['Macacos hidráulicos e tartarugas', 'Mudanças completas de plantas fabris', 'Desmontagem e remontagem de máquinas', 'Intervenções com janelas de parada reduzidas', 'Atuação em indústrias de alto risco'] },
      { num: '03', title: 'Locação de Equipamentos', intro: 'Contratos flexíveis de curto e longo prazo com frota revisada, documentada e homologada por engenheiros.', body: 'Cada equipamento é inspecionado antes da mobilização e entregue com laudos e histórico de manutenção atualizados.', feats: ['Manutenção preventiva inclusa', 'Laudos e histórico disponíveis', 'Contratos de curto, médio e longo prazo', 'Atendimento em escala nacional', 'Suporte técnico 24/7'] },
      { num: '04', title: 'Linha Amarela (Retroescavadeira)', intro: 'Retroescavadeiras, pás carregadeiras e escavadeiras hidráulicas para terraplanagem, escavação e movimentação de solo.', body: 'Equipamentos em pleno estado operacional, com toda a documentação e certificações vigentes para mobilização imediata.', feats: ['Retroescavadeiras de diversas capacidades', 'Pás carregadeiras articuladas', 'Escavadeiras hidráulicas', 'Operadores certificados e experientes', 'Documentação e revisões em dia'] },
      { num: '05', title: 'Transporte de Cargas Especiais', intro: 'Transporte rodoviário de cargas superdimensionadas e pesadas com carretas especiais, escolta e licenças vigentes.', body: 'Rotas planejadas por engenheiro especializado, com apoio de escolta credenciada e toda a documentação exigida pelos órgãos reguladores.', feats: ['Carretas prancha simples e extensivas', 'Caminhão-guindauto de alta capacidade', 'Licenças DNIT/DER vigentes', 'Escolta credenciada', 'Planejamento de rota por engenheiro'] },
    ],
  },
  esg: {
    heroEyebrow: 'Responsabilidade corporativa', heroSub: 'O futuro do transporte pesado caminha lado a lado com sustentabilidade, ética e responsabilidade social.', heroCrumb: 'ESG',
    visionEyebrow: 'Nossa visão', visionSub: 'Nossa agenda ESG é um programa estruturado com metas, indicadores e prestação de contas para todos os stakeholders.',
    esgItems: [
      { title: 'Ambiental', desc: 'Modernização da frota para reduzir emissões, descarte correto de resíduos e conscientização ambiental em todas as operações.' },
      { title: 'Social', desc: 'Treinamentos de segurança, valorização dos colaboradores e programas de desenvolvimento profissional contínuo.' },
      { title: 'Governança', desc: 'Transparência total, políticas anticorrupção e Canal Confidencial de Denúncias disponível a todos os stakeholders.' },
    ],
    cardsEyebrow: 'Nossas iniciativas', cardsTitle: 'Práticas que fazem a diferença',
    cards: [
      { title: 'Redução de emissões', desc: 'Renovação da frota com equipamentos de menor consumo e rotas otimizadas.' },
      { title: 'Zero acidentes graves', desc: 'Histórico de zero acidentes graves nos últimos 10 anos de operação.' },
      { title: 'Valorização de talentos', desc: 'Plano de carreira, capacitação contínua e qualidade de vida para todos.' },
      { title: 'Transparência total', desc: 'Código de conduta, canal de denúncias e auditoria externa anual.' },
    ],
    bannerTag: 'Canal Confidencial de Denúncias', bannerTitle: 'Relate uma situação de forma segura', bannerDesc: 'Canal totalmente confidencial para colaboradores, clientes e fornecedores.', bannerBtn: 'Acessar canal',
  },
  certificacoes: {
    heroEyebrow: 'Garantia de qualidade', heroSub: 'Cumprimento rigoroso das principais normas nacionais e internacionais para máxima segurança operacional.', heroCrumb: 'Certificações',
    certDescs: ['Sistema de Gestão da Qualidade certificado e auditado por organismo acreditado internacionalmente.', 'Conformidade com as normas de gestão ambiental, movimentação e segurança em máquinas.', 'Sistema de Gestão de Saúde e Segurança Ocupacional aplicado em 100% das operações.', 'Signatários dos Princípios de Empoderamento das Mulheres, promovendo equidade no ambiente de trabalho.', 'Adesão ao Pacto Global da ONU, comprometendo-se com os dez princípios de sustentabilidade e direitos humanos.', 'Associados ao Instituto Ethos, referência em práticas de responsabilidade social empresarial no Brasil.'],
    downloadTitle: 'Baixar certificado PDF',
    whyEyebrow: 'Por que isso importa', whyLead: 'As certificações do Grupo Maxpesa são o resultado de anos de trabalho sistemático para garantir que cada operação seja executada com o mais alto padrão de qualidade e segurança.', whyBody: 'Para o contratante, isso representa previsibilidade, redução de riscos e um parceiro que sabe exatamente o que está fazendo.', whyBtn: 'Solicitar proposta técnica',
    items: [
      { t: 'Auditorias anuais independentes', d: 'Revisão completa dos processos por auditores externos credenciados.' },
      { t: 'Operadores com habilitação atualizada', d: 'Cursos de reciclagem obrigatórios e registros NR-11 sempre válidos.' },
      { t: 'Laudos técnicos disponíveis', d: 'Documentação completa entregue ao contratante antes de cada operação.' },
      { t: 'Cobertura de seguros em 100% das operações', d: 'RCTR-C e responsabilidade civil ativa em todas as mobilizações.' },
      { t: 'Memorial de cálculo de rigging', d: 'Engenheiro responsável assina cada içamento de equipamento pesado.' },
    ],
    docEyebrow: 'Documentação disponível', docSub: 'Enviamos toda a documentação técnica para análise prévia antes da contratação.', docBtn: 'Solicitar documentação',
  },
  blog: { heroEye: 'Insights & Novidades', heroTitle: 'Blog', heroSub: 'Artigos, novidades e conteúdo técnico sobre movimentação de cargas, logística pesada e boas práticas operacionais.', featured: 'Destaque', readMore: 'Leia o artigo completo', readMoreShort: 'Leia mais', ctaEye: 'Fique por dentro', ctaTitle: 'Conteúdo técnico para decisões mais inteligentes', ctaSub: 'Acompanhe novidades sobre movimentação pesada, segurança operacional e logística industrial.', ctaBtn: 'Fale com um especialista' },
  frota: {
    heroEyebrow: 'Locação de Equipamentos', heroSub: 'Frota própria com manutenção preventiva, operadores certificados e suporte 24/7. Consulte disponibilidade e solicite locação.', heroCrumb: 'Nossa Frota',
    cta: 'Solicitar Locação', filterMetaSingle: 'equipamento disponível para locação', filterMetaPlural: 'equipamentos disponíveis para locação',
    categories: { all: 'Todos', guindastes: 'Guindastes', munck: 'Cam. Guindauto', empilhadeiras: 'Empilhadeiras', 'linha-amarela': 'Linha Amarela', plataforma: 'Plat. Elevatória', especiais: 'Cargas Especiais' },
    specLabels: { 'Capacidade': 'Capacidade', 'Pluma': 'Pluma', 'Rotação': 'Rotação', 'Alcance': 'Alcance', 'Acionam.': 'Acionam.', 'Balde': 'Balde', 'Prof. max': 'Prof. max', 'Tração': 'Tração', 'Peso op.': 'Peso op.', 'Profundid.': 'Profundid.', 'Alt. trab.': 'Alt. trab.', 'Comprimento': 'Comprimento', 'Licença': 'Licença', 'Elevação': 'Elevação', 'Plataf.': 'Plataf.', 'Eixos': 'Eixos' },
    itemNames: { 1: 'Guindaste Rodoviário Telescópico', 2: 'Guindaste Treliçado', 3: 'Guindaste Rodoviário Telescópico', 5: 'Caminhão-Guindauto', 6: 'Caminhão-Guindauto', 7: 'Escavadeira Hidráulica', 8: 'Pá Carregadeira', 9: 'Plataforma Articulada', 10: 'Plataforma Tesoura', 11: 'Carreta Carga Seca', 12: 'Carreta Extensiva', 13: 'Carreta Baú Sider', 14: 'Carreta Baú', 15: 'Carreta Prancha', 16: 'Linha de Eixo', 17: 'Empilhadeira Elétrica', 18: 'Empilhadeira Diesel' },
  },
  footer: { desc: 'Referência nacional em movimentações de carga complexas, transportes pesados e engenharia de rigging com mais de 25 anos de mercado.', address: 'Matriz — Duque de Caxias, RJ', navTitle: 'Navegação', navLinks: ['Início', 'A Empresa', 'Nossos Serviços', 'Nossa Frota', 'ESG', 'Certificações', 'Trabalhe Conosco'], svcTitle: 'Serviços', svcLinks: ['Mov. Horizontal e Vertical', 'Movimentação de Cargas', 'Locação de Equipamentos', 'Linha Amarela', 'Transporte Especial'], contactTitle: 'Contato', reportLink: 'Canal de Denúncias', contactLink: 'Fale Conosco', copyright: 'Todos os direitos reservados.' },
  toast: { title: 'Mensagem enviada com sucesso', subtitle: 'Retornaremos em até 2 horas úteis.' },
  trabalhe: { heroEyebrow: 'Junte-se ao time', heroSub: 'Faça parte de um grupo com mais de 25 anos movendo o Brasil. Envie seu currículo e aguarde nosso contato.', heroCrumb: 'Trabalhe Conosco' },
  contato: { heroEyebrow: 'Fale conosco', heroSub: 'Nossa equipe comercial responde com proposta técnica em até 2 horas úteis.', heroCrumb: 'Contato' },
}

// ─── EN ───────────────────────────────────────────────────────────────────────
const EN = {
  flag: '🇺🇸', name: 'English', short: 'EN',
  nav: { home: 'Home', company: 'The Company', services: 'Services', fleet: 'Our Fleet', esg: 'ESG', certifications: 'Certifications', blog: 'Blog', report: 'Report', careers: 'Work With Us', quote: 'Get a Quote' },
  serviceItems: ['Horizontal & Vertical Cargo Handling', 'Cargo Movement', 'Equipment Rental', 'Yellow Line (Backhoe)', 'Special Cargo Transport'],
  home: {
    heroTag: 'Over 25 years moving Brazil',
    heroSub: 'High-performance solutions in cargo handling, heavy transport, industrial removal and equipment rental.',
    heroBtnServices: 'Our Services', heroBtnQuote: 'Request a Quote',
    statLabel1: 'Years of tradition', statLabel2: 'Projects executed', statLabel3: 'Operational commitment', statSub4: '9001 Certified',
    svcEyebrow: 'What we do', svcTitle: 'Solutions for any logistics challenge', svcSub: 'Modern equipment and certified teams to ensure the safety of your cargo.',
    svcMore: 'Learn more', svcBtn: 'See all services',
    services: [
      { title: 'Horizontal & Vertical Cargo Handling', desc: 'Lifting and positioning of heavy equipment and structures with high-complexity rigging, NR-11 certified operators and engineer-signed load calculations.' },
      { title: 'Cargo Movement', desc: 'Planning and execution of factory layout changes, machine positioning and disassembly of industrial equipment with minimal production downtime.' },
      { title: 'Equipment Rental', desc: 'Modern and diversified fleet available in short and long-term contracts — cranes, truck-mounted cranes and yellow line — with preventive maintenance and 24/7 support.' },
      { title: 'Yellow Line (Backhoe)', desc: 'Backhoes, wheel loaders and hydraulic excavators for earthmoving, excavation and soil handling, with certified operators and current documentation.' },
      { title: 'Special Cargo Transport', desc: 'Road transport of oversized cargo with special trailers, truck-mounted crane, credentialed escort, DNIT/DER permits and engineer-planned routes.' },
    ],
    splitEyebrow: 'Our history', splitTitle: '25 years building with trust',
    splitBody1: 'We founded Grupo Maxpesa with the purpose of transforming heavy logistics in Brazil — with safety, precision and commitment in every operation.',
    splitBody2: 'Today we are a national reference, with a modern proprietary fleet, in-house engineering and certified teams.',
    splitBtnCompany: 'Meet the company', splitBtnContact: 'Talk to our team',
    whyEyebrow: 'Our differentials', whyTitle: 'Why choose Maxpesa', whySub: 'Committed to safety, precision and results in every operation.',
    why: [
      { title: 'Safety above all', desc: 'Rigorous NR-11 program, periodic inspections and continuous training.' },
      { title: 'Proprietary engineering', desc: 'Rigging plan and load calculation delivered before each mobilisation.' },
      { title: '24/7 availability', desc: 'Fleet with preventive maintenance and support available for emergencies.' },
    ],
    ctaEyebrow: 'Talk to a specialist', ctaTitle: 'Ready for your next project?', ctaSub: 'Our team responds with a technical proposal within 2 hours.',
    ctaBtnQuote: 'Request a quote', ctaBtnWpp: 'WhatsApp',
    clientsEyebrow: 'Who trusts Maxpesa', clientsTitle: 'Partners building Brazil with us',
  },
  empresa: {
    heroEyebrow: 'Our History', heroSub: 'Founded to transform heavy logistics in Brazil — with safety, precision and commitment.', heroCrumb: 'The Company',
    aboutEyebrow: 'Who we are',
    aboutLead: 'Grupo Maxpesa was born with the purpose of transforming heavy logistics in Brazil — delivering rigging engineering solutions with safety and precision.',
    aboutBody: 'We operate strategically with integrated solutions for industry, commerce and infrastructure. Our non-negotiable commitment to safety allows us to tackle the biggest logistics challenges with millimetric precision.',
    statLabel1: 'Years of tradition', statLabel2: 'Projects executed', statLabel3: 'Commitment',
    tlEyebrow: 'Our journey', tlBtn: 'Talk to our team',
    timeline: [
      { year: '1998', title: 'Founding of Grupo Maxpesa', desc: 'Operations began in Rio de Janeiro focused on vertical handling and crane rental.' },
      { year: '2003', title: 'Fleet expansion and new segments', desc: 'Incorporation of truck-mounted cranes and special trailers, opening the oversized cargo segment.' },
      { year: '2009', title: 'ISO 9001 Certification', desc: 'Formal recognition of the quality management system, consolidating world-class processes.' },
      { year: '2014', title: 'Major infrastructure projects', desc: 'Participation in nationally significant works, including petrochemical and energy generation projects.' },
      { year: '2023', title: '25 years — new milestone', desc: 'Fleet renewal, investment in rigging technology and expansion to new Brazilian states.' },
    ],
    mvvEyebrow: 'Our essence', mvvTitle: 'Mission, Vision & Values', mvvSub: 'The fundamental principles that guide every decision and define who we are.',
    mvv: [
      { label: 'Mission', items: ['High-quality products and services', 'Positive and collaborative work environment', 'Positive impact on clients and employees', 'Responsibility toward the community'] },
      { label: 'Vision', items: ['Reference company in the segment', 'Innovative and technological solutions', 'Ethical principles in all decisions', 'Environmental responsibility and sustainable growth'] },
      { label: 'Values', items: ['Ethics and honesty', 'Integrity and discipline', 'Transparency', 'Social responsibility', 'Obsession with safety'] },
    ],
    opEyebrow: 'How we operate', opTitle: 'Operational pillars', opSub: 'The practical foundations that guide every operation, team and delivery of Grupo Maxpesa.',
    values: [
      { title: 'Safety', desc: 'The safety of employees and clients is non-negotiable. Each operation begins and ends with rigorous NR-11 protocols.' },
      { title: 'Technical excellence', desc: 'Proprietary engineering, certified equipment and continuously trained operators guarantee the highest standard.' },
      { title: 'Commitment', desc: 'Deadline, scope and quality are commitments made and honoured. Our reputation is 25 years of kept promises.' },
      { title: 'Innovation', desc: 'Constant investment in new technologies and methodologies to always offer the best solution.' },
      { title: 'Relationships', desc: 'Long-term partnerships based on trust, transparency and results are our greatest achievement.' },
      { title: 'Responsibility', desc: 'We value our teams, respect communities and operate with environmental awareness.' },
    ],
    locEyebrow: 'Where we are', locTitle: 'Our headquarters', locSub: 'Located in Duque de Caxias — RJ, the Grupo Maxpesa headquarters serves the entire national territory.', locBadge: 'HQ', locMapTitle: 'Grupo Maxpesa Headquarters',
  },
  servicos: {
    heroEyebrow: 'Full portfolio', heroSub: 'Certified equipment and specialised teams for every type of logistics challenge.', heroCrumb: 'Services',
    btn: 'Request a quote', specialEyebrow: "Can't find what you need?", specialBtn: 'Talk to a specialist',
    services: [
      { num: '01', title: 'Horizontal & Vertical Cargo Handling', intro: 'Lifting, positioning and transfer of heavy equipment and structures with high-complexity rigging.', body: 'Our team prepares custom rigging studies with engineer-signed load calculations and RRT — ensuring absolute safety in every operation.', feats: ['Telescopic cranes from 25 t to 1,200 t', 'NR-11 certified operators', 'Engineer-signed load calculation and RRT', 'Confined-space lifts', 'RCTR-C coverage included'] },
      { num: '02', title: 'Cargo Movement', intro: 'Planning and execution of factory layout changes, machine positioning and industrial equipment disassembly.', body: 'Our engineering team prepares an intervention schedule ensuring minimum production downtime.', feats: ['Hydraulic jacks and skates', 'Complete factory layout changes', 'Machine disassembly and reassembly', 'Interventions with reduced downtime windows', 'Operations in high-risk industries'] },
      { num: '03', title: 'Equipment Rental', intro: 'Flexible short and long-term contracts with a revised, documented, engineer-approved fleet.', body: 'Each piece of equipment is inspected before mobilisation and delivered with updated reports and maintenance history.', feats: ['Preventive maintenance included', 'Reports and history available', 'Short, medium and long-term contracts', 'Nationwide coverage', '24/7 technical support'] },
      { num: '04', title: 'Yellow Line (Backhoe)', intro: 'Backhoes, wheel loaders and hydraulic excavators for earthmoving, excavation and soil handling.', body: 'Equipment in full operational condition, with all documentation and current certifications for immediate mobilisation.', feats: ['Backhoes of various capacities', 'Articulated wheel loaders', 'Hydraulic excavators', 'Certified and experienced operators', 'Up-to-date documentation and inspections'] },
      { num: '05', title: 'Special Cargo Transport', intro: 'Road transport of oversized and heavy cargo with special trailers, escort and current permits.', body: 'Routes planned by a specialised engineer, with credentialed escort support and all documentation required by regulatory bodies.', feats: ['Simple and extendable flatbed trailers', 'High-capacity truck-mounted crane', 'Current DNIT/DER permits', 'Credentialed escort', 'Route planning by engineer'] },
    ],
  },
  esg: {
    heroEyebrow: 'Corporate responsibility', heroSub: 'The future of heavy transport goes hand in hand with sustainability, ethics and social responsibility.', heroCrumb: 'ESG',
    visionEyebrow: 'Our vision', visionSub: 'Our ESG agenda is a structured programme with targets, indicators and accountability for all stakeholders.',
    esgItems: [
      { title: 'Environmental', desc: 'Fleet modernisation to reduce emissions, proper waste disposal and environmental awareness across all operations.' },
      { title: 'Social', desc: 'Safety training, employee recognition and continuous professional development programmes.' },
      { title: 'Governance', desc: 'Full transparency, anti-corruption policies and a Confidential Whistleblower Channel available to all stakeholders.' },
    ],
    cardsEyebrow: 'Our initiatives', cardsTitle: 'Practices that make a difference',
    cards: [
      { title: 'Emissions reduction', desc: 'Fleet renewal with lower-consumption equipment and optimised routes.' },
      { title: 'Zero serious accidents', desc: 'Record of zero serious accidents in the last 10 years of operation.' },
      { title: 'Talent recognition', desc: 'Career plans, continuous training and quality of life for everyone.' },
      { title: 'Full transparency', desc: 'Code of conduct, whistleblower channel and annual external audit.' },
    ],
    bannerTag: 'Confidential Whistleblower Channel', bannerTitle: 'Report a situation safely', bannerDesc: 'Fully confidential channel for employees, clients and suppliers.', bannerBtn: 'Access channel',
  },
  certificacoes: {
    heroEyebrow: 'Quality assurance', heroSub: 'Rigorous compliance with the main national and international standards for maximum operational safety.', heroCrumb: 'Certifications',
    certDescs: ['Quality Management System certified and audited by an internationally accredited body.', 'Compliance with environmental management, handling and machinery safety standards.', 'Occupational Health and Safety Management System applied in 100% of operations.', "Signatories of the Women's Empowerment Principles, promoting equity in the workplace.", 'Adherence to the UN Global Compact, committing to the ten principles of sustainability and human rights.', 'Associated with Instituto Ethos, reference in corporate social responsibility practices in Brazil.'],
    downloadTitle: 'Download PDF certificate',
    whyEyebrow: 'Why this matters', whyLead: 'Grupo Maxpesa certifications are the result of years of systematic work to ensure that every operation is carried out to the highest standard of quality and safety.', whyBody: 'For the contracting party, this means predictability, risk reduction and a partner who knows exactly what they are doing.', whyBtn: 'Request a technical proposal',
    items: [
      { t: 'Annual independent audits', d: 'Complete review of processes by accredited external auditors.' },
      { t: 'Operators with updated licences', d: 'Mandatory refresher courses and NR-11 records always valid.' },
      { t: 'Technical reports available', d: 'Complete documentation delivered to the contractor before each operation.' },
      { t: 'Insurance coverage in 100% of operations', d: 'RCTR-C and active civil liability in all mobilisations.' },
      { t: 'Rigging load calculation', d: 'Responsible engineer signs every heavy equipment lift.' },
    ],
    docEyebrow: 'Documentation available', docSub: 'We send all technical documentation for prior review before contracting.', docBtn: 'Request documentation',
  },
  blog: { heroEye: 'Insights & News', heroTitle: 'Blog', heroSub: 'Articles, news and technical content on cargo handling, heavy logistics and best operational practices.', featured: 'Featured', readMore: 'Read the full article', readMoreShort: 'Read more', ctaEye: 'Stay informed', ctaTitle: 'Technical content for smarter decisions', ctaSub: 'Follow news on heavy handling, operational safety and industrial logistics.', ctaBtn: 'Talk to a specialist' },
  frota: {
    heroEyebrow: 'Equipment Rental', heroSub: 'Proprietary fleet with preventive maintenance, certified operators and 24/7 support. Check availability and request rental.', heroCrumb: 'Our Fleet',
    cta: 'Request Rental', filterMetaSingle: 'piece of equipment available for rental', filterMetaPlural: 'pieces of equipment available for rental',
    categories: { all: 'All', guindastes: 'Cranes', munck: 'Truck Cranes', empilhadeiras: 'Forklifts', 'linha-amarela': 'Yellow Line', plataforma: 'Aerial Lifts', especiais: 'Special Cargo' },
    specLabels: { 'Capacidade': 'Capacity', 'Pluma': 'Boom', 'Rotação': 'Rotation', 'Alcance': 'Reach', 'Acionam.': 'Drive', 'Balde': 'Bucket', 'Prof. max': 'Max depth', 'Tração': 'Traction', 'Peso op.': 'Op. weight', 'Profundid.': 'Depth', 'Alt. trab.': 'Work height', 'Comprimento': 'Length', 'Licença': 'Permit', 'Elevação': 'Lift height', 'Plataf.': 'Platform', 'Eixos': 'Axles' },
    itemNames: { 1: 'Telescopic Mobile Crane', 2: 'Lattice Boom Crane', 3: 'Telescopic Mobile Crane', 5: 'Truck-Mounted Crane', 6: 'Truck-Mounted Crane', 7: 'Hydraulic Excavator', 8: 'Wheel Loader', 9: 'Articulating Boom Lift', 10: 'Scissor Lift', 11: 'Flatbed Trailer', 12: 'Extendable Trailer', 13: 'Sider Box Trailer', 14: 'Box Trailer', 15: 'Low-Bed Trailer', 16: 'Axle Line', 17: 'Electric Forklift', 18: 'Diesel Forklift' },
  },
  footer: { desc: 'National reference in complex cargo handling, heavy transport and rigging engineering with over 25 years in the market.', address: 'HQ — Duque de Caxias, RJ', navTitle: 'Navigation', navLinks: ['Home', 'The Company', 'Our Services', 'Our Fleet', 'ESG', 'Certifications', 'Work With Us'], svcTitle: 'Services', svcLinks: ['Horiz. & Vert. Handling', 'Cargo Movement', 'Equipment Rental', 'Yellow Line', 'Special Transport'], contactTitle: 'Contact', reportLink: 'Whistleblower Channel', contactLink: 'Contact Us', copyright: 'All rights reserved.' },
  toast: { title: 'Message sent successfully', subtitle: 'We will respond within 2 business hours.' },
  trabalhe: { heroEyebrow: 'Join the team', heroSub: 'Be part of a group with over 25 years moving Brazil. Send your CV and await our contact.', heroCrumb: 'Work With Us' },
  contato: { heroEyebrow: 'Get in touch', heroSub: 'Our commercial team responds with a technical proposal within 2 business hours.', heroCrumb: 'Contact' },
}

// ─── ES ───────────────────────────────────────────────────────────────────────
const ES = {
  flag: '🇪🇸', name: 'Español', short: 'ES',
  nav: { home: 'Inicio', company: 'La Empresa', services: 'Servicios', fleet: 'Nuestra Flota', esg: 'ESG', certifications: 'Certificaciones', blog: 'Blog', report: 'Denuncia', careers: 'Trabaje Con Nosotros', quote: 'Presupuesto' },
  serviceItems: ['Movimiento Horizontal y Vertical de Cargas', 'Movimiento de Cargas', 'Alquiler de Equipos', 'Línea Amarilla (Retroexcavadora)', 'Transporte de Cargas Especiales'],
  home: {
    heroTag: 'Más de 25 años moviendo Brasil',
    heroSub: 'Soluciones de alto rendimiento en manejo de cargas, transporte pesado, remoción industrial y alquiler de equipos.',
    heroBtnServices: 'Nuestros Servicios', heroBtnQuote: 'Solicitar Presupuesto',
    statLabel1: 'Años de tradición', statLabel2: 'Proyectos ejecutados', statLabel3: 'Compromiso operacional', statSub4: '9001 Certificado',
    svcEyebrow: 'Qué hacemos', svcTitle: 'Soluciones para cualquier desafío logístico', svcSub: 'Equipos modernos y equipos certificados para garantizar la seguridad de su carga.',
    svcMore: 'Ver más', svcBtn: 'Ver todos los servicios',
    services: [
      { title: 'Movimiento Horizontal y Vertical de Cargas', desc: 'Izaje y posicionamiento de equipos y estructuras pesadas con aparejamiento de alta complejidad, operadores certificados NR-11 y memoria de cálculo firmada por ingeniero.' },
      { title: 'Movimiento de Cargas', desc: 'Planificación y ejecución de cambios de layout fabril, posicionamiento de máquinas y desmontaje de equipos industriales con la menor paralización posible en producción.' },
      { title: 'Alquiler de Equipos', desc: 'Flota moderna y diversificada disponible en contratos de corto y largo plazo — grúas, camión grúa y línea amarilla — con mantenimiento preventivo y soporte 24/7.' },
      { title: 'Línea Amarilla (Retroexcavadora)', desc: 'Retroexcavadoras, cargadoras de ruedas y excavadoras hidráulicas para movimiento de tierra, excavación y manejo de suelo, con operadores certificados y documentación vigente.' },
      { title: 'Transporte de Cargas Especiales', desc: 'Transporte por carretera de cargas sobredimensionadas con remolques especiales, camión grúa, escolta acreditada, permisos DNIT/DER y ruta planificada por ingeniero.' },
    ],
    splitEyebrow: 'Nuestra historia', splitTitle: '25 años construyendo con confianza',
    splitBody1: 'Fundamos Grupo Maxpesa con el propósito de transformar la logística pesada en Brasil — con seguridad, precisión y compromiso en cada operación.',
    splitBody2: 'Hoy somos referencia nacional, con flota propia moderna, ingeniería propietaria y equipos certificados.',
    splitBtnCompany: 'Conoce la empresa', splitBtnContact: 'Hablar con el equipo',
    whyEyebrow: 'Nuestros diferenciales', whyTitle: 'Por qué elegir Maxpesa', whySub: 'Comprometidos con seguridad, precisión y resultado en cada operación.',
    why: [
      { title: 'Seguridad ante todo', desc: 'Riguroso programa NR-11, inspecciones periódicas y capacitación continua.' },
      { title: 'Ingeniería propia', desc: 'Plan de aparejamiento y memoria de cálculo entregados antes de cada movilización.' },
      { title: 'Disponibilidad 24/7', desc: 'Flota con mantenimiento preventivo y soporte disponible para emergencias.' },
    ],
    ctaEyebrow: 'Hable con un especialista', ctaTitle: 'Listo para su próximo proyecto?', ctaSub: 'Nuestro equipo responde con propuesta técnica en hasta 2 horas.',
    ctaBtnQuote: 'Solicitar presupuesto', ctaBtnWpp: 'WhatsApp',
    clientsEyebrow: 'Quiénes confían en Maxpesa', clientsTitle: 'Socios que construyen Brasil con nosotros',
  },
  empresa: {
    heroEyebrow: 'Nuestra Historia', heroSub: 'Fundados para transformar la logística pesada en Brasil — con seguridad, precisión y compromiso.', heroCrumb: 'La Empresa',
    aboutEyebrow: 'Quiénes somos',
    aboutLead: 'Grupo Maxpesa nació con el propósito de transformar la logística pesada en Brasil — ofreciendo soluciones de ingeniería de aparejamiento con seguridad y precisión.',
    aboutBody: 'Actuamos estratégicamente con soluciones integradas para industria, comercio e infraestructura. Nuestro compromiso innegociable con la seguridad nos permite enfrentar los mayores desafíos logísticos con precisión milimétrica.',
    statLabel1: 'Años de tradición', statLabel2: 'Proyectos ejecutados', statLabel3: 'Compromiso',
    tlEyebrow: 'Nuestra trayectoria', tlBtn: 'Hable con nuestro equipo',
    timeline: [
      { year: '1998', title: 'Fundación de Grupo Maxpesa', desc: 'Inicio de operaciones en Río de Janeiro con foco en movimiento vertical y alquiler de grúas.' },
      { year: '2003', title: 'Expansión de la flota y nuevos segmentos', desc: 'Incorporación de camiones grúa y remolques especiales, abriendo el segmento de cargas sobredimensionadas.' },
      { year: '2009', title: 'Certificación ISO 9001', desc: 'Reconocimiento formal del sistema de gestión de calidad, consolidando procesos de clase mundial.' },
      { year: '2014', title: 'Grandes proyectos de infraestructura', desc: 'Participación en obras de relevancia nacional, incluidos proyectos petroquímicos y de generación de energía.' },
      { year: '2023', title: '25 años — nuevo nivel', desc: 'Renovación de la flota, inversión en tecnología de aparejamiento y expansión a nuevos estados brasileños.' },
    ],
    mvvEyebrow: 'Nuestra esencia', mvvTitle: 'Misión, Visión y Valores', mvvSub: 'Los principios fundamentales que orientan cada decisión y definen quiénes somos.',
    mvv: [
      { label: 'Misión', items: ['Productos y servicios de alta calidad', 'Ambiente de trabajo positivo y colaborativo', 'Impacto positivo en clientes y colaboradores', 'Responsabilidad con la comunidad'] },
      { label: 'Visión', items: ['Empresa de referencia en el segmento', 'Soluciones innovadoras y tecnológicas', 'Principios éticos en todas las decisiones', 'Responsabilidad ambiental y crecimiento sostenible'] },
      { label: 'Valores', items: ['Ética y honestidad', 'Integridad y disciplina', 'Transparencia', 'Responsabilidad social', 'Obsesión por la seguridad'] },
    ],
    opEyebrow: 'Cómo operamos', opTitle: 'Pilares operacionales', opSub: 'Los cimientos prácticos que orientan cada operación, equipo y entrega de Grupo Maxpesa.',
    values: [
      { title: 'Seguridad', desc: 'La seguridad de colaboradores y clientes es innegociable. Cada operación comienza y termina con protocolos rigurosos de NR-11.' },
      { title: 'Excelencia técnica', desc: 'Ingeniería propia, equipos certificados y operadores con formación continua garantizan el estándar más alto.' },
      { title: 'Compromiso', desc: 'Plazo, alcance y calidad son compromisos asumidos y honrados. Nuestra reputación es 25 años de palabra cumplida.' },
      { title: 'Innovación', desc: 'Inversión constante en nuevas tecnologías y metodologías para ofrecer siempre la mejor solución.' },
      { title: 'Relaciones', desc: 'Las alianzas de largo plazo basadas en confianza, transparencia y resultados son nuestro mayor logro.' },
      { title: 'Responsabilidad', desc: 'Valoramos a nuestros equipos, respetamos comunidades y operamos con conciencia ambiental.' },
    ],
    locEyebrow: 'Dónde estamos', locTitle: 'Nuestra sede', locSub: 'Ubicada en Duque de Caxias — RJ, la sede de Grupo Maxpesa atiende todo el territorio nacional.', locBadge: 'Sede', locMapTitle: 'Sede Grupo Maxpesa',
  },
  servicos: {
    heroEyebrow: 'Portafolio completo', heroSub: 'Equipos certificados y equipos especializados para cada tipo de desafío logístico.', heroCrumb: 'Servicios',
    btn: 'Solicitar cotización', specialEyebrow: 'No encontró lo que necesita?', specialBtn: 'Hablar con un especialista',
    services: [
      { num: '01', title: 'Movimiento Horizontal y Vertical de Cargas', intro: 'Izaje, posicionamiento y transferencia de equipos y estructuras pesadas con aparejamiento de alta complejidad.', body: 'Nuestro equipo elabora estudios de aparejamiento personalizados con memoria de cálculo y RRT firmados por ingeniero responsable.', feats: ['Grúas telescópicas de 25 t a 1.200 t', 'Operadores certificados NR-11', 'Memoria de cálculo y RRT firmados', 'Izajes en espacios confinados', 'Cobertura RCTR-C incluida'] },
      { num: '02', title: 'Movimiento de Cargas', intro: 'Planificación y ejecución de cambios de layout fabril, posicionamiento de máquinas y desmontaje de equipos industriales.', body: 'Nuestra ingeniería elabora cronograma de intervención garantizando la menor paralización posible en la línea de producción.', feats: ['Gatos hidráulicos y patines', 'Cambios completos de plantas fabriles', 'Desmontaje y remontaje de máquinas', 'Intervenciones con ventanas de parada reducidas', 'Actuación en industrias de alto riesgo'] },
      { num: '03', title: 'Alquiler de Equipos', intro: 'Contratos flexibles de corto y largo plazo con flota revisada, documentada y homologada por ingenieros.', body: 'Cada equipo es inspeccionado antes de la movilización y entregado con informes e historial de mantenimiento actualizados.', feats: ['Mantenimiento preventivo incluido', 'Informes e historial disponibles', 'Contratos de corto, mediano y largo plazo', 'Atención a escala nacional', 'Soporte técnico 24/7'] },
      { num: '04', title: 'Línea Amarilla (Retroexcavadora)', intro: 'Retroexcavadoras, cargadoras de ruedas y excavadoras hidráulicas para movimiento de tierra, excavación y manejo de suelo.', body: 'Equipos en pleno estado operacional, con toda la documentación y certificaciones vigentes para movilización inmediata.', feats: ['Retroexcavadoras de diversas capacidades', 'Cargadoras de ruedas articuladas', 'Excavadoras hidráulicas', 'Operadores certificados y experimentados', 'Documentación y revisiones al día'] },
      { num: '05', title: 'Transporte de Cargas Especiales', intro: 'Transporte por carretera de cargas sobredimensionadas y pesadas con remolques especiales, escolta y permisos vigentes.', body: 'Rutas planificadas por ingeniero especializado, con apoyo de escolta acreditada y toda la documentación exigida por los organismos reguladores.', feats: ['Remolques plataforma simples y extensibles', 'Camión grúa de alta capacidad', 'Permisos DNIT/DER vigentes', 'Escolta acreditada', 'Planificación de ruta por ingeniero'] },
    ],
  },
  esg: {
    heroEyebrow: 'Responsabilidad corporativa', heroSub: 'El futuro del transporte pesado va de la mano con sostenibilidad, ética y responsabilidad social.', heroCrumb: 'ESG',
    visionEyebrow: 'Nuestra visión', visionSub: 'Nuestra agenda ESG es un programa estructurado con metas, indicadores y rendición de cuentas para todos los grupos de interés.',
    esgItems: [
      { title: 'Ambiental', desc: 'Modernización de la flota para reducir emisiones, disposición correcta de residuos y concientización ambiental en todas las operaciones.' },
      { title: 'Social', desc: 'Capacitaciones de seguridad, valoración de los colaboradores y programas de desarrollo profesional continuo.' },
      { title: 'Gobernanza', desc: 'Transparencia total, políticas anticorrupción y Canal Confidencial de Denuncias disponible para todos los grupos de interés.' },
    ],
    cardsEyebrow: 'Nuestras iniciativas', cardsTitle: 'Prácticas que marcan la diferencia',
    cards: [
      { title: 'Reducción de emisiones', desc: 'Renovación de la flota con equipos de menor consumo y rutas optimizadas.' },
      { title: 'Cero accidentes graves', desc: 'Historial de cero accidentes graves en los últimos 10 años de operación.' },
      { title: 'Valoración de talentos', desc: 'Plan de carrera, capacitación continua y calidad de vida para todos.' },
      { title: 'Transparencia total', desc: 'Código de conducta, canal de denuncias y auditoría externa anual.' },
    ],
    bannerTag: 'Canal Confidencial de Denuncias', bannerTitle: 'Reporte una situación de forma segura', bannerDesc: 'Canal totalmente confidencial para colaboradores, clientes y proveedores.', bannerBtn: 'Acceder al canal',
  },
  certificacoes: {
    heroEyebrow: 'Garantía de calidad', heroSub: 'Cumplimiento riguroso de las principales normas nacionales e internacionales para máxima seguridad operacional.', heroCrumb: 'Certificaciones',
    certDescs: ['Sistema de Gestión de Calidad certificado y auditado por organismo acreditado internacionalmente.', 'Conformidad con las normas de gestión ambiental, movimiento y seguridad en máquinas.', 'Sistema de Gestión de Salud y Seguridad Ocupacional aplicado en el 100% de las operaciones.', 'Signatarios de los Principios de Empoderamiento de las Mujeres, promoviendo equidad en el ambiente laboral.', 'Adhesión al Pacto Global de la ONU, comprometiéndose con los diez principios de sostenibilidad y derechos humanos.', 'Asociados al Instituto Ethos, referencia en prácticas de responsabilidad social empresarial en Brasil.'],
    downloadTitle: 'Descargar certificado PDF',
    whyEyebrow: 'Por qué importa', whyLead: 'Las certificaciones de Grupo Maxpesa son el resultado de años de trabajo sistemático para garantizar que cada operación se ejecute con el más alto estándar de calidad y seguridad.', whyBody: 'Para el contratante, esto representa previsibilidad, reducción de riesgos y un socio que sabe exactamente lo que hace.', whyBtn: 'Solicitar propuesta técnica',
    items: [
      { t: 'Auditorías anuales independientes', d: 'Revisión completa de los procesos por auditores externos acreditados.' },
      { t: 'Operadores con habilitación actualizada', d: 'Cursos de reciclaje obligatorios y registros NR-11 siempre vigentes.' },
      { t: 'Informes técnicos disponibles', d: 'Documentación completa entregada al contratante antes de cada operación.' },
      { t: 'Cobertura de seguros en el 100% de las operaciones', d: 'RCTR-C y responsabilidad civil activa en todas las movilizaciones.' },
      { t: 'Memoria de cálculo de aparejamiento', d: 'Ingeniero responsable firma cada izaje de equipo pesado.' },
    ],
    docEyebrow: 'Documentación disponible', docSub: 'Enviamos toda la documentación técnica para análisis previo antes de la contratación.', docBtn: 'Solicitar documentación',
  },
  blog: { heroEye: 'Perspectivas y Novedades', heroTitle: 'Blog', heroSub: 'Artículos, novedades y contenido técnico sobre manejo de cargas, logística pesada y buenas prácticas operacionales.', featured: 'Destacado', readMore: 'Leer el artículo completo', readMoreShort: 'Leer más', ctaEye: 'Manténgase informado', ctaTitle: 'Contenido técnico para decisiones más inteligentes', ctaSub: 'Siga novedades sobre manejo pesado, seguridad operacional y logística industrial.', ctaBtn: 'Hablar con un especialista' },
  frota: {
    heroEyebrow: 'Alquiler de Equipos', heroSub: 'Flota propia con mantenimiento preventivo, operadores certificados y soporte 24/7. Consulte disponibilidad y solicite alquiler.', heroCrumb: 'Nuestra Flota',
    cta: 'Solicitar Alquiler', filterMetaSingle: 'equipo disponible para alquiler', filterMetaPlural: 'equipos disponibles para alquiler',
    categories: { all: 'Todos', guindastes: 'Grúas', munck: 'Cam. Grúa', empilhadeiras: 'Montacargas', 'linha-amarela': 'Línea Amarilla', plataforma: 'Plat. Elevadora', especiais: 'Cargas Especiales' },
    specLabels: { 'Capacidade': 'Capacidad', 'Pluma': 'Pluma', 'Rotação': 'Rotación', 'Alcance': 'Alcance', 'Acionam.': 'Accionam.', 'Balde': 'Cucharón', 'Prof. max': 'Prof. máx', 'Tração': 'Tracción', 'Peso op.': 'Peso op.', 'Profundid.': 'Profundidad', 'Alt. trab.': 'Alt. trabajo', 'Comprimento': 'Longitud', 'Licença': 'Licencia', 'Elevação': 'Elevación', 'Plataf.': 'Plataforma', 'Eixos': 'Ejes' },
    itemNames: { 1: 'Grúa Móvil Telescópica', 2: 'Grúa de Celosía', 3: 'Grúa Móvil Telescópica', 5: 'Camión Grúa', 6: 'Camión Grúa', 7: 'Excavadora Hidráulica', 8: 'Cargadora de Ruedas', 9: 'Plataforma Articulada', 10: 'Plataforma Tijera', 11: 'Remolque Plataforma', 12: 'Remolque Extensible', 13: 'Remolque Caja Sider', 14: 'Remolque Caja', 15: 'Remolque de Cama Baja', 16: 'Línea de Ejes', 17: 'Montacargas Eléctrico', 18: 'Montacargas Diésel' },
  },
  footer: { desc: 'Referencia nacional en movimiento de cargas complejas, transporte pesado e ingeniería de aparejamiento con más de 25 años de mercado.', address: 'Sede — Duque de Caxias, RJ', navTitle: 'Navegación', navLinks: ['Inicio', 'La Empresa', 'Nuestros Servicios', 'Nuestra Flota', 'ESG', 'Certificaciones', 'Trabaje Con Nosotros'], svcTitle: 'Servicios', svcLinks: ['Mov. Horiz. y Vertical', 'Movimiento de Cargas', 'Alquiler de Equipos', 'Línea Amarilla', 'Transporte Especial'], contactTitle: 'Contacto', reportLink: 'Canal de Denuncias', contactLink: 'Contáctenos', copyright: 'Todos los derechos reservados.' },
  toast: { title: 'Mensaje enviado con éxito', subtitle: 'Le responderemos en hasta 2 horas hábiles.' },
  trabalhe: { heroEyebrow: 'Únase al equipo', heroSub: 'Sea parte de un grupo con más de 25 años moviendo Brasil. Envíe su CV y espere nuestro contacto.', heroCrumb: 'Trabaje Con Nosotros' },
  contato: { heroEyebrow: 'Contáctenos', heroSub: 'Nuestro equipo comercial responde con propuesta técnica en hasta 2 horas hábiles.', heroCrumb: 'Contacto' },
}

// ─── DE ───────────────────────────────────────────────────────────────────────
const DE = {
  flag: '🇩🇪', name: 'Deutsch', short: 'DE',
  nav: { home: 'Startseite', company: 'Das Unternehmen', services: 'Leistungen', fleet: 'Unsere Flotte', esg: 'ESG', certifications: 'Zertifizierungen', blog: 'Blog', report: 'Meldung', careers: 'Karriere', quote: 'Angebot' },
  serviceItems: ['Horizontaler & Vertikaler Gütertransport', 'Güterumschlag', 'Geräteverleih', 'Gelbe Linie (Baggerlader)', 'Schwerguttransport'],
  home: {
    heroTag: 'Über 25 Jahre bewegen wir Brasilien',
    heroSub: 'Hochleistungslösungen im Güterumschlag, Schwertransport, Industriedemontage und Geräteverleih.',
    heroBtnServices: 'Unsere Leistungen', heroBtnQuote: 'Angebot anfordern',
    statLabel1: 'Jahre Tradition', statLabel2: 'Ausgeführte Projekte', statLabel3: 'Betriebliche Zuverlässigkeit', statSub4: '9001 Zertifiziert',
    svcEyebrow: 'Was wir tun', svcTitle: 'Lösungen für jede Logistikherausforderung', svcSub: 'Moderne Geräte und zertifizierte Teams für die Sicherheit Ihrer Ladung.',
    svcMore: 'Mehr erfahren', svcBtn: 'Alle Leistungen ansehen',
    services: [
      { title: 'Horizontaler & Vertikaler Gütertransport', desc: 'Heben und Positionieren von schweren Geräten und Strukturen mit komplexem Rigging, NR-11-zertifizierten Bedienern und ingenieurgezeichneten Lastberechnungen.' },
      { title: 'Güterumschlag', desc: 'Planung und Durchführung von Fabrik-Layout-Änderungen, Maschinenpositionierung und Demontage von Industrieanlagen mit minimalen Produktionsausfällen.' },
      { title: 'Geräteverleih', desc: 'Moderne und vielfältige Flotte in kurz- und langfristigen Verträgen — Krane, LKW-Krane und Gelbe Linie — mit Wartung und 24/7-Support.' },
      { title: 'Gelbe Linie (Baggerlader)', desc: 'Baggerlader, Radlader und Hydraulikbagger für Erdarbeiten, Aushub und Bodenbewegung mit zertifizierten Bedienern und aktueller Dokumentation.' },
      { title: 'Schwerguttransport', desc: 'Straßentransport von Übergütern mit Spezialaufliegern, LKW-Kran, beglaubigter Begleitung, DNIT/DER-Genehmigungen und ingenieurgeplantem Streckenverlauf.' },
    ],
    splitEyebrow: 'Unsere Geschichte', splitTitle: '25 Jahre Aufbau mit Vertrauen',
    splitBody1: 'Wir gründeten Grupo Maxpesa mit dem Ziel, die schwere Logistik in Brasilien zu transformieren — mit Sicherheit, Präzision und Engagement in jeder Operation.',
    splitBody2: 'Heute sind wir nationale Referenz, mit moderner Eigenflotte, hauseigener Ingenieurtechnik und zertifizierten Teams.',
    splitBtnCompany: 'Das Unternehmen kennenlernen', splitBtnContact: 'Mit dem Team sprechen',
    whyEyebrow: 'Unsere Stärken', whyTitle: 'Warum Maxpesa wählen?', whySub: 'Engagiert für Sicherheit, Präzision und Ergebnisse bei jeder Operation.',
    why: [
      { title: 'Sicherheit über alles', desc: 'Strenges NR-11-Programm, regelmäßige Inspektionen und kontinuierliche Schulungen.' },
      { title: 'Eigene Ingenieurtechnik', desc: 'Rigging-Plan und Lastberechnung werden vor jeder Mobilisierung übergeben.' },
      { title: '24/7-Verfügbarkeit', desc: 'Flotte mit vorbeugender Wartung und Notfallsupport.' },
    ],
    ctaEyebrow: 'Mit einem Experten sprechen', ctaTitle: 'Bereit für Ihr nächstes Projekt?', ctaSub: 'Unser Team antwortet mit einem technischen Angebot innerhalb von 2 Stunden.',
    ctaBtnQuote: 'Angebot anfordern', ctaBtnWpp: 'WhatsApp',
    clientsEyebrow: 'Wer Maxpesa vertraut', clientsTitle: 'Partner, die Brasilien gemeinsam mit uns aufbauen',
  },
  empresa: {
    heroEyebrow: 'Unsere Geschichte', heroSub: 'Gegründet zur Transformation der schweren Logistik in Brasilien — mit Sicherheit, Präzision und Engagement.', heroCrumb: 'Das Unternehmen',
    aboutEyebrow: 'Wer wir sind',
    aboutLead: 'Grupo Maxpesa wurde gegründet, um die schwere Logistik in Brasilien zu transformieren — mit sicheren und präzisen Rigging-Engineering-Lösungen.',
    aboutBody: 'Wir agieren strategisch mit integrierten Lösungen für Industrie, Handel und Infrastruktur. Unser kompromissloses Sicherheitsengagement ermöglicht es uns, die größten Logistikherausforderungen mit Millimetergenauigkeit zu meistern.',
    statLabel1: 'Jahre Tradition', statLabel2: 'Ausgeführte Projekte', statLabel3: 'Engagement',
    tlEyebrow: 'Unser Werdegang', tlBtn: 'Mit unserem Team sprechen',
    timeline: [
      { year: '1998', title: 'Gründung der Grupo Maxpesa', desc: 'Betriebsaufnahme in Rio de Janeiro mit Fokus auf vertikalen Umschlag und Kranvermietung.' },
      { year: '2003', title: 'Flottenausbau und neue Segmente', desc: 'Aufnahme von LKW-Kranen und Spezialaufliegern, Erschließung des Übergut-Segments.' },
      { year: '2009', title: 'ISO 9001-Zertifizierung', desc: 'Formale Anerkennung des Qualitätsmanagementsystems, Konsolidierung weltklasse Prozesse.' },
      { year: '2014', title: 'Große Infrastrukturprojekte', desc: 'Beteiligung an national bedeutenden Bauvorhaben, einschließlich petrochemischer und Energieprojekte.' },
      { year: '2023', title: '25 Jahre — neue Stufe', desc: 'Flottenreneuerung, Investition in Rigging-Technologie und Expansion in neue brasilianische Bundesstaaten.' },
    ],
    mvvEyebrow: 'Unser Wesen', mvvTitle: 'Mission, Vision & Werte', mvvSub: 'Die grundlegenden Prinzipien, die jede Entscheidung lenken und definieren, wer wir sind.',
    mvv: [
      { label: 'Mission', items: ['Hochwertige Produkte und Dienstleistungen', 'Positives und kollaboratives Arbeitsumfeld', 'Positive Wirkung auf Kunden und Mitarbeiter', 'Verantwortung gegenüber der Gemeinschaft'] },
      { label: 'Vision', items: ['Referenzunternehmen im Segment', 'Innovative und technologische Lösungen', 'Ethische Grundsätze in allen Entscheidungen', 'Umweltverantwortung und nachhaltiges Wachstum'] },
      { label: 'Werte', items: ['Ethik und Ehrlichkeit', 'Integrität und Disziplin', 'Transparenz', 'Soziale Verantwortung', 'Besessenheit für Sicherheit'] },
    ],
    opEyebrow: 'Wie wir arbeiten', opTitle: 'Operative Säulen', opSub: 'Die praktischen Grundlagen jeder Operation, jedes Teams und jeder Lieferung von Grupo Maxpesa.',
    values: [
      { title: 'Sicherheit', desc: 'Die Sicherheit von Mitarbeitern und Kunden ist nicht verhandelbar. Jede Operation beginnt und endet mit strengen NR-11-Protokollen.' },
      { title: 'Technische Exzellenz', desc: 'Eigene Ingenieurtechnik, zertifizierte Geräte und kontinuierlich geschulte Bediener garantieren den höchsten Standard.' },
      { title: 'Engagement', desc: 'Termine, Umfang und Qualität sind Verpflichtungen, die eingegangen und eingehalten werden. Unser Ruf ist 25 Jahre gehaltenes Wort.' },
      { title: 'Innovation', desc: 'Kontinuierliche Investitionen in neue Technologien und Methoden, um stets die beste Lösung zu bieten.' },
      { title: 'Beziehungen', desc: 'Langfristige Partnerschaften auf Basis von Vertrauen, Transparenz und Ergebnissen sind unser größter Erfolg.' },
      { title: 'Verantwortung', desc: 'Wir schätzen unsere Teams, respektieren Gemeinschaften und handeln mit Umweltbewusstsein.' },
    ],
    locEyebrow: 'Wo wir sind', locTitle: 'Unser Hauptsitz', locSub: 'Der Hauptsitz von Grupo Maxpesa in Duque de Caxias — RJ bedient das gesamte nationale Territorium.', locBadge: 'Hauptsitz', locMapTitle: 'Grupo Maxpesa Hauptsitz',
  },
  servicos: {
    heroEyebrow: 'Vollständiges Portfolio', heroSub: 'Zertifizierte Geräte und spezialisierte Teams für jeden Logistikherausforderungstyp.', heroCrumb: 'Leistungen',
    btn: 'Angebot anfordern', specialEyebrow: 'Nicht gefunden, was Sie suchen?', specialBtn: 'Mit einem Experten sprechen',
    services: [
      { num: '01', title: 'Horizontaler & Vertikaler Gütertransport', intro: 'Heben, Positionieren und Transfer schwerer Geräte und Strukturen mit hochkomplexem Rigging.', body: 'Unser Team erstellt maßgeschneiderte Rigging-Studien mit Lastberechnung und RRT, unterzeichnet vom verantwortlichen Ingenieur.', feats: ['Teleskopkrane von 25 t bis 1.200 t', 'NR-11-zertifizierte Bediener', 'Unterschriebene Lastberechnung und RRT', 'Hebungen in beengten Räumen', 'RCTR-C-Deckung inklusive'] },
      { num: '02', title: 'Güterumschlag', intro: 'Planung und Durchführung von Fabrik-Layout-Änderungen, Maschinenpositionierung und Demontage von Industrieanlagen.', body: 'Unser Engineering erstellt einen Interventionsplan, der minimale Produktionsausfälle gewährleistet.', feats: ['Hydraulische Wagenheber und Gleitkufen', 'Vollständige Fabrikverlagerungen', 'Maschinendemontage und -montage', 'Eingriffe mit reduziertem Stillstandsfenster', 'Einsatz in risikoreichen Industrien'] },
      { num: '03', title: 'Geräteverleih', intro: 'Flexible Kurz- und Langzeitverträge mit geprüfter, dokumentierter, ingenieurgeprüfter Flotte.', body: 'Jedes Gerät wird vor der Mobilisierung inspiziert und mit aktuellen Berichten und Wartungshistorie übergeben.', feats: ['Vorbeugende Wartung inklusive', 'Berichte und Wartungshistorie verfügbar', 'Kurz-, Mittel- und Langzeitverträge', 'Bundesweite Betreuung', '24/7 technischer Support'] },
      { num: '04', title: 'Gelbe Linie (Baggerlader)', intro: 'Baggerlader, Radlader und Hydraulikbagger für Erdarbeiten, Aushub und Bodenbewegung.', body: 'Geräte in vollem Betriebszustand, mit aller aktuellen Dokumentation und Zertifizierungen für sofortige Mobilisierung.', feats: ['Baggerlader verschiedener Kapazitäten', 'Knickgelenk-Radlader', 'Hydraulikbagger', 'Zertifizierte und erfahrene Bediener', 'Aktuelle Dokumentation und Inspektionen'] },
      { num: '05', title: 'Schwerguttransport', intro: 'Straßentransport von Übergütern und schweren Lasten mit Spezialaufliegern, Begleitung und gültigen Genehmigungen.', body: 'Routen von Fachingenieur geplant, mit beglaubigter Begleitunterstützung und aller von den Regulierungsbehörden geforderten Dokumentation.', feats: ['Einfache und ausziehbare Tiefbettauflieger', 'LKW-Kran mit hoher Kapazität', 'Gültige DNIT/DER-Genehmigungen', 'Beglaubigte Begleitung', 'Streckenplanung durch Ingenieur'] },
    ],
  },
  esg: {
    heroEyebrow: 'Unternehmensverantwortung', heroSub: 'Die Zukunft des Schwertransports geht Hand in Hand mit Nachhaltigkeit, Ethik und sozialer Verantwortung.', heroCrumb: 'ESG',
    visionEyebrow: 'Unsere Vision', visionSub: 'Unsere ESG-Agenda ist ein strukturiertes Programm mit Zielen, Indikatoren und Rechenschaftspflicht für alle Stakeholder.',
    esgItems: [
      { title: 'Umwelt', desc: 'Flottenmodernisierung zur Emissionsreduzierung, korrekte Abfallentsorgung und Umweltbewusstsein in allen Operationen.' },
      { title: 'Soziales', desc: 'Sicherheitsschulungen, Mitarbeiterwertschätzung und kontinuierliche Berufsförderungsprogramme.' },
      { title: 'Governance', desc: 'Vollständige Transparenz, Antikorruptionsrichtlinien und vertraulicher Hinweisgeberkanal für alle Stakeholder.' },
    ],
    cardsEyebrow: 'Unsere Initiativen', cardsTitle: 'Praktiken, die einen Unterschied machen',
    cards: [
      { title: 'Emissionsreduzierung', desc: 'Flottenreneuerung mit kraftstoffsparenden Geräten und optimierten Routen.' },
      { title: 'Null schwere Unfälle', desc: 'Bilanz von null schweren Unfällen in den letzten 10 Betriebsjahren.' },
      { title: 'Talentförderung', desc: 'Karriereplan, kontinuierliche Schulung und Lebensqualität für alle.' },
      { title: 'Vollständige Transparenz', desc: 'Verhaltenskodex, Hinweisgeberkanal und jährliche externe Prüfung.' },
    ],
    bannerTag: 'Vertraulicher Hinweisgeberkanal', bannerTitle: 'Melden Sie eine Situation sicher', bannerDesc: 'Vollständig vertraulicher Kanal für Mitarbeiter, Kunden und Lieferanten.', bannerBtn: 'Kanal aufrufen',
  },
  certificacoes: {
    heroEyebrow: 'Qualitätssicherung', heroSub: 'Strikte Einhaltung der wichtigsten nationalen und internationalen Normen für maximale Betriebssicherheit.', heroCrumb: 'Zertifizierungen',
    certDescs: ['Qualitätsmanagementsystem, zertifiziert und geprüft von einer international akkreditierten Stelle.', 'Konformität mit Umweltmanagement-, Handhabungs- und Maschinensicherheitsnormen.', 'Arbeitsschutz-Managementsystem in 100% der Operationen angewendet.', 'Unterzeichner der Grundsätze zur Stärkung der Stellung der Frau, Förderung von Gleichberechtigung am Arbeitsplatz.', 'Beitritt zum UN Global Compact, Verpflichtung zu den zehn Prinzipien für Nachhaltigkeit und Menschenrechte.', 'Mitglied des Instituto Ethos, Referenz für unternehmerische Sozialverantwortung in Brasilien.'],
    downloadTitle: 'PDF-Zertifikat herunterladen',
    whyEyebrow: 'Warum das wichtig ist', whyLead: 'Die Zertifizierungen von Grupo Maxpesa sind das Ergebnis jahrelanger systematischer Arbeit, um sicherzustellen, dass jede Operation nach dem höchsten Qualitäts- und Sicherheitsstandard durchgeführt wird.', whyBody: 'Für den Auftraggeber bedeutet dies Planbarkeit, Risikominimierung und einen Partner, der genau weiß, was er tut.', whyBtn: 'Technisches Angebot anfordern',
    items: [
      { t: 'Jährliche unabhängige Prüfungen', d: 'Vollständige Prozessüberprüfung durch akkreditierte externe Prüfer.' },
      { t: 'Bediener mit aktueller Zulassung', d: 'Obligatorische Auffrischungskurse und stets gültige NR-11-Registrierungen.' },
      { t: 'Technische Berichte verfügbar', d: 'Vollständige Dokumentation vor jeder Operation an den Auftraggeber übergeben.' },
      { t: 'Versicherungsschutz bei 100% der Operationen', d: 'RCTR-C und aktive Haftpflicht bei allen Mobilisierungen.' },
      { t: 'Rigging-Lastberechnung', d: 'Verantwortlicher Ingenieur unterzeichnet jeden Schwerlasthub.' },
    ],
    docEyebrow: 'Dokumentation verfügbar', docSub: 'Wir senden alle technischen Unterlagen zur Vorabprüfung vor der Beauftragung.', docBtn: 'Dokumentation anfordern',
  },
  blog: { heroEye: 'Einblicke & Neuigkeiten', heroTitle: 'Blog', heroSub: 'Artikel, Neuigkeiten und technische Inhalte zu Güterumschlag, Schwertransport und operativen Best Practices.', featured: 'Empfohlen', readMore: 'Vollständigen Artikel lesen', readMoreShort: 'Mehr lesen', ctaEye: 'Bleiben Sie informiert', ctaTitle: 'Technische Inhalte für klügere Entscheidungen', ctaSub: 'Folgen Sie Neuigkeiten zu Schwertransport, Betriebssicherheit und Industrielogistik.', ctaBtn: 'Mit einem Experten sprechen' },
  frota: {
    heroEyebrow: 'Geräteverleih', heroSub: 'Eigenflotte mit vorbeugender Wartung, zertifizierten Bedienern und 24/7-Support. Verfügbarkeit prüfen und Verleih anfordern.', heroCrumb: 'Unsere Flotte',
    cta: 'Verleih anfragen', filterMetaSingle: 'Gerät verfügbar für Verleih', filterMetaPlural: 'Geräte verfügbar für Verleih',
    categories: { all: 'Alle', guindastes: 'Krane', munck: 'LKW-Krane', empilhadeiras: 'Gabelstapler', 'linha-amarela': 'Gelbe Linie', plataforma: 'Hebebühnen', especiais: 'Schwergut' },
    specLabels: { 'Capacidade': 'Tragkraft', 'Pluma': 'Ausleger', 'Rotação': 'Drehung', 'Alcance': 'Reichweite', 'Acionam.': 'Antrieb', 'Balde': 'Schaufel', 'Prof. max': 'Max. Tiefe', 'Tração': 'Traktion', 'Peso op.': 'Betriebsgew.', 'Profundid.': 'Tiefe', 'Alt. trab.': 'Arbeitshöhe', 'Comprimento': 'Länge', 'Licença': 'Zulassung', 'Elevação': 'Hubhöhe', 'Plataf.': 'Plattform', 'Eixos': 'Achsen' },
    itemNames: { 1: 'Teleskopkran', 2: 'Gittermastkran', 3: 'Teleskopkran', 5: 'LKW-Kran', 6: 'LKW-Kran', 7: 'Hydraulikbagger', 8: 'Radlader', 9: 'Gelenkausleger-Hebebühne', 10: 'Scherenhebebühne', 11: 'Trockenfrachtanhänger', 12: 'Ausziehbarer Anhänger', 13: 'Sider-Kastenanhänger', 14: 'Kastenanhänger', 15: 'Tiefladeanhänger', 16: 'Achslinie', 17: 'Elektro-Gabelstapler', 18: 'Diesel-Gabelstapler' },
  },
  footer: { desc: 'Nationale Referenz im komplexen Güterumschlag, Schwertransport und Rigging-Engineering mit über 25 Jahren Markterfahrung.', address: 'Zentrale — Duque de Caxias, RJ', navTitle: 'Navigation', navLinks: ['Startseite', 'Das Unternehmen', 'Unsere Leistungen', 'Unsere Flotte', 'ESG', 'Zertifizierungen', 'Karriere'], svcTitle: 'Leistungen', svcLinks: ['Horiz. & Vert. Transport', 'Güterumschlag', 'Geräteverleih', 'Gelbe Linie', 'Schwerguttransport'], contactTitle: 'Kontakt', reportLink: 'Hinweisgeberkanal', contactLink: 'Kontakt', copyright: 'Alle Rechte vorbehalten.' },
  toast: { title: 'Nachricht erfolgreich gesendet', subtitle: 'Wir antworten innerhalb von 2 Geschäftsstunden.' },
  trabalhe: { heroEyebrow: 'Werden Sie Teil des Teams', heroSub: 'Treten Sie einer Gruppe bei, die seit über 25 Jahren Brasilien bewegt. Senden Sie Ihren Lebenslauf und warten Sie auf unsere Rückmeldung.', heroCrumb: 'Karriere' },
  contato: { heroEyebrow: 'Kontakt aufnehmen', heroSub: 'Unser Vertriebsteam antwortet mit einem technischen Angebot innerhalb von 2 Geschäftsstunden.', heroCrumb: 'Kontakt' },
}

// ─── FR ───────────────────────────────────────────────────────────────────────
const FR = {
  flag: '🇫🇷', name: 'Français', short: 'FR',
  nav: { home: 'Accueil', company: "L'Entreprise", services: 'Services', fleet: 'Notre Flotte', esg: 'ESG', certifications: 'Certifications', blog: 'Blog', report: 'Signalement', careers: 'Travailler Avec Nous', quote: 'Devis' },
  serviceItems: ['Manutention Horizontale & Verticale', 'Déplacement de Charges', 'Location de Matériel', 'Ligne Jaune (Rétrocaveuse)', 'Transport de Charges Spéciales'],
  home: {
    heroTag: 'Plus de 25 ans à faire bouger le Brésil',
    heroSub: 'Solutions haute performance en manutention de charges, transport lourd, déménagement industriel et location de matériel.',
    heroBtnServices: 'Nos Services', heroBtnQuote: 'Demander un Devis',
    statLabel1: 'Ans de tradition', statLabel2: 'Projets réalisés', statLabel3: 'Engagement opérationnel', statSub4: '9001 Certifié',
    svcEyebrow: 'Ce que nous faisons', svcTitle: 'Solutions pour tout défi logistique', svcSub: 'Équipements modernes et équipes certifiées pour garantir la sécurité de votre chargement.',
    svcMore: 'En savoir plus', svcBtn: 'Voir tous les services',
    services: [
      { title: 'Manutention Horizontale & Verticale', desc: 'Levage et positionnement de matériels et structures lourds avec gréage de haute complexité, opérateurs certifiés NR-11 et note de calcul signée par ingénieur.' },
      { title: 'Déplacement de Charges', desc: 'Planification et exécution de changements de layout industriel, positionnement de machines et démontage avec un arrêt de production minimal.' },
      { title: 'Location de Matériel', desc: 'Flotte moderne disponible en contrats court et long terme — grues, camions-grues et ligne jaune — avec maintenance préventive et support 24/7.' },
      { title: 'Ligne Jaune (Rétrocaveuse)', desc: 'Rétrocaveuses, chargeuses sur pneus et pelleteuses hydrauliques pour terrassement, excavation et déplacement de sol, avec opérateurs certifiés.' },
      { title: 'Transport de Charges Spéciales', desc: 'Transport routier de charges surdimensionnées avec semi-remorques spéciaux, camion-grue, escorte agréée, permis DNIT/DER et itinéraire planifié par ingénieur.' },
    ],
    splitEyebrow: 'Notre histoire', splitTitle: '25 ans à construire avec confiance',
    splitBody1: 'Nous avons fondé Grupo Maxpesa avec pour objectif de transformer la logistique lourde au Brésil — avec sécurité, précision et engagement dans chaque opération.',
    splitBody2: "Aujourd'hui nous sommes une référence nationale, avec une flotte propre moderne, une ingénierie propriétaire et des équipes certifiées.",
    splitBtnCompany: "Découvrir l'entreprise", splitBtnContact: "Parler à l'équipe",
    whyEyebrow: 'Nos atouts', whyTitle: 'Pourquoi choisir Maxpesa ?', whySub: 'Engagés pour la sécurité, la précision et les résultats à chaque opération.',
    why: [
      { title: 'La sécurité avant tout', desc: 'Programme NR-11 rigoureux, inspections périodiques et formation continue.' },
      { title: 'Ingénierie propriétaire', desc: 'Plan de gréage et note de calcul remis avant chaque mobilisation.' },
      { title: 'Disponibilité 24/7', desc: 'Flotte avec maintenance préventive et support disponible pour les urgences.' },
    ],
    ctaEyebrow: 'Parler à un spécialiste', ctaTitle: 'Prêt pour votre prochain projet ?', ctaSub: 'Notre équipe répond avec une proposition technique en 2 heures.',
    ctaBtnQuote: 'Demander un devis', ctaBtnWpp: 'WhatsApp',
    clientsEyebrow: 'Qui fait confiance à Maxpesa', clientsTitle: 'Partenaires qui construisent le Brésil avec nous',
  },
  empresa: {
    heroEyebrow: 'Notre Histoire', heroSub: 'Fondés pour transformer la logistique lourde au Brésil — avec sécurité, précision et engagement.', heroCrumb: "L'Entreprise",
    aboutEyebrow: 'Qui nous sommes',
    aboutLead: "Grupo Maxpesa est né avec pour vocation de transformer la logistique lourde au Brésil — en offrant des solutions d'ingénierie de gréage avec sécurité et précision.",
    aboutBody: "Nous agissons de manière stratégique avec des solutions intégrées pour l'industrie, le commerce et les infrastructures. Notre engagement inébranlable envers la sécurité nous permet de relever les plus grands défis logistiques avec une précision millimétrique.",
    statLabel1: 'Ans de tradition', statLabel2: 'Projets réalisés', statLabel3: 'Engagement',
    tlEyebrow: 'Notre parcours', tlBtn: 'Parler à notre équipe',
    timeline: [
      { year: '1998', title: 'Fondation de Grupo Maxpesa', desc: "Début des opérations à Rio de Janeiro axées sur la manutention verticale et la location de grues." },
      { year: '2003', title: 'Expansion de la flotte et nouveaux segments', desc: "Intégration de camions-grues et de semi-remorques spéciaux, ouvrant le segment des charges surdimensionnées." },
      { year: '2009', title: 'Certification ISO 9001', desc: 'Reconnaissance formelle du système de management de la qualité, consolidant des processus de classe mondiale.' },
      { year: '2014', title: "Grands projets d'infrastructure", desc: "Participation à des chantiers d'importance nationale, incluant des projets pétrochimiques et de production d'énergie." },
      { year: '2023', title: '25 ans — nouveau palier', desc: 'Renouvellement de la flotte, investissement dans la technologie de gréage et expansion dans de nouveaux États brésiliens.' },
    ],
    mvvEyebrow: 'Notre essence', mvvTitle: 'Mission, Vision & Valeurs', mvvSub: 'Les principes fondamentaux qui guident chaque décision et définissent qui nous sommes.',
    mvv: [
      { label: 'Mission', items: ['Produits et services de haute qualité', 'Environnement de travail positif et collaboratif', 'Impact positif sur les clients et les collaborateurs', 'Responsabilité envers la communauté'] },
      { label: 'Vision', items: ['Entreprise de référence dans le secteur', 'Solutions innovantes et technologiques', 'Principes éthiques dans toutes les décisions', 'Responsabilité environnementale et croissance durable'] },
      { label: 'Valeurs', items: ['Éthique et honnêteté', 'Intégrité et discipline', 'Transparence', 'Responsabilité sociale', 'Obsession pour la sécurité'] },
    ],
    opEyebrow: 'Comment nous opérons', opTitle: 'Piliers opérationnels', opSub: "Les fondements pratiques qui guident chaque opération, chaque équipe et chaque livraison de Grupo Maxpesa.",
    values: [
      { title: 'Sécurité', desc: "La sécurité des collaborateurs et des clients est non négociable. Chaque opération commence et se termine avec des protocoles NR-11 rigoureux." },
      { title: 'Excellence technique', desc: "Ingénierie propriétaire, équipements certifiés et opérateurs en formation continue garantissent le plus haut standard." },
      { title: 'Engagement', desc: "Délais, périmètre et qualité sont des engagements pris et tenus. Notre réputation, c'est 25 ans de parole donnée." },
      { title: 'Innovation', desc: "Investissement constant dans les nouvelles technologies et méthodologies pour toujours proposer la meilleure solution." },
      { title: 'Relations', desc: 'Les partenariats à long terme fondés sur la confiance, la transparence et les résultats sont notre plus grande réussite.' },
      { title: 'Responsabilité', desc: "Nous valorisons nos équipes, respectons les communautés et opérons avec une conscience environnementale." },
    ],
    locEyebrow: 'Où nous sommes', locTitle: 'Notre siège social', locSub: 'Situé à Duque de Caxias — RJ, le siège de Grupo Maxpesa sert tout le territoire national.', locBadge: 'Siège', locMapTitle: 'Siège Social Grupo Maxpesa',
  },
  servicos: {
    heroEyebrow: 'Portefeuille complet', heroSub: 'Équipements certifiés et équipes spécialisées pour chaque type de défi logistique.', heroCrumb: 'Services',
    btn: 'Demander un devis', specialEyebrow: 'Vous ne trouvez pas ce dont vous avez besoin ?', specialBtn: 'Parler à un spécialiste',
    services: [
      { num: '01', title: 'Manutention Horizontale & Verticale', intro: "Levage, positionnement et transfert d'équipements et de structures lourdes avec gréage de haute complexité.", body: "Notre équipe élabore des études de gréage personnalisées avec note de calcul et RRT signés par l'ingénieur responsable.", feats: ['Grues télescopiques de 25 t à 1 200 t', 'Opérateurs certifiés NR-11', 'Note de calcul et RRT signés', 'Levages en espaces confinés', 'Couverture RCTR-C incluse'] },
      { num: '02', title: 'Déplacement de Charges', intro: "Planification et exécution de changements de layout d'usine, positionnement de machines et démontage d'équipements industriels.", body: "Notre ingénierie établit un calendrier d'intervention garantissant un arrêt de production minimal.", feats: ['Vérins hydrauliques et patins', "Déménagements complets de sites industriels", 'Démontage et remontage de machines', 'Interventions avec fenêtres réduredes', 'Interventions dans des industries à haut risque'] },
      { num: '03', title: 'Location de Matériel', intro: 'Contrats flexibles à court et long terme avec une flotte révisée, documentée et homologuée par des ingénieurs.', body: "Chaque équipement est inspecté avant la mobilisation et livré avec des rapports et un historique de maintenance à jour.", feats: ['Maintenance préventive incluse', 'Rapports et historique disponibles', 'Contrats court, moyen et long terme', 'Couverture nationale', 'Support technique 24/7'] },
      { num: '04', title: 'Ligne Jaune (Rétrocaveuse)', intro: 'Rétrocaveuses, chargeuses sur pneus et pelleteuses hydrauliques pour terrassement, excavation et déplacement de sol.', body: "Équipements en plein état opérationnel, avec toute la documentation et les certifications à jour pour une mobilisation immédiate.", feats: ['Rétrocaveuses de diverses capacités', 'Chargeuses sur pneus articulées', 'Pelleteuses hydrauliques', 'Opérateurs certifiés et expérimentés', 'Documentation et contrôles à jour'] },
      { num: '05', title: 'Transport de Charges Spéciales', intro: 'Transport routier de charges surdimensionnées et lourdes avec semi-remorques spéciaux, escorte et permis valides.', body: "Itinéraires planifiés par un ingénieur spécialisé, avec escorte agréée et toute la documentation exigée par les organismes de régulation.", feats: ['Semi-remorques plateaux simples et extensibles', 'Camion-grue haute capacité', 'Permis DNIT/DER valides', 'Escorte agréée', 'Planification de trajet par ingénieur'] },
    ],
  },
  esg: {
    heroEyebrow: 'Responsabilité corporative', heroSub: "L'avenir du transport lourd va de pair avec la durabilité, l'éthique et la responsabilité sociale.", heroCrumb: 'ESG',
    visionEyebrow: 'Notre vision', visionSub: "Notre agenda ESG est un programme structuré avec des objectifs, des indicateurs et une reddition de comptes pour toutes les parties prenantes.",
    esgItems: [
      { title: 'Environnemental', desc: 'Modernisation de la flotte pour réduire les émissions, élimination correcte des déchets et sensibilisation environnementale dans toutes les opérations.' },
      { title: 'Social', desc: 'Formations à la sécurité, valorisation des collaborateurs et programmes de développement professionnel continu.' },
      { title: 'Gouvernance', desc: 'Transparence totale, politiques anticorruption et canal confidentiel de signalement disponible pour toutes les parties prenantes.' },
    ],
    cardsEyebrow: 'Nos initiatives', cardsTitle: 'Des pratiques qui font la différence',
    cards: [
      { title: 'Réduction des émissions', desc: 'Renouvellement de la flotte avec des équipements moins consommateurs et des itinéraires optimisés.' },
      { title: 'Zéro accident grave', desc: "Bilan de zéro accident grave au cours des 10 dernières années d'exploitation." },
      { title: 'Valorisation des talents', desc: 'Plan de carrière, formation continue et qualité de vie pour tous.' },
      { title: 'Transparence totale', desc: "Code de conduite, canal de signalement et audit externe annuel." },
    ],
    bannerTag: 'Canal Confidentiel de Signalement', bannerTitle: 'Signalez une situation en toute sécurité', bannerDesc: 'Canal entièrement confidentiel pour les collaborateurs, clients et fournisseurs.', bannerBtn: 'Accéder au canal',
  },
  certificacoes: {
    heroEyebrow: 'Garantie de qualité', heroSub: 'Conformité rigoureuse aux principales normes nationales et internationales pour une sécurité opérationnelle maximale.', heroCrumb: 'Certifications',
    certDescs: ["Système de Management de la Qualité certifié et audité par un organisme accrédité internationalement.", "Conformité aux normes de gestion environnementale, de manutention et de sécurité des machines.", "Système de Management de la Santé et de la Sécurité au Travail appliqué dans 100% des opérations.", "Signataires des Principes d'autonomisation des femmes, promouvant l'équité en milieu de travail.", "Adhésion au Pacte mondial de l'ONU, engagement envers les dix principes de durabilité et des droits de l'homme.", "Associés à l'Instituto Ethos, référence en pratiques de responsabilité sociale des entreprises au Brésil."],
    downloadTitle: 'Télécharger le certificat PDF',
    whyEyebrow: "Pourquoi c'est important", whyLead: "Les certifications de Grupo Maxpesa sont le fruit d'années de travail systématique pour garantir que chaque opération est réalisée selon le plus haut standard de qualité et de sécurité.", whyBody: "Pour le donneur d'ordre, cela représente prévisibilité, réduction des risques et un partenaire qui sait exactement ce qu'il fait.", whyBtn: 'Demander une proposition technique',
    items: [
      { t: 'Audits annuels indépendants', d: 'Révision complète des processus par des auditeurs externes accrédités.' },
      { t: 'Opérateurs avec licences à jour', d: 'Formations de recyclage obligatoires et enregistrements NR-11 toujours valides.' },
      { t: 'Rapports techniques disponibles', d: "Documentation complète remise au donneur d'ordre avant chaque opération." },
      { t: "Couverture d'assurance dans 100% des opérations", d: 'RCTR-C et responsabilité civile active dans toutes les mobilisations.' },
      { t: 'Note de calcul de gréage', d: "L'ingénieur responsable signe chaque levage d'équipement lourd." },
    ],
    docEyebrow: 'Documentation disponible', docSub: 'Nous envoyons toute la documentation technique pour examen préalable avant la contractualisation.', docBtn: 'Demander la documentation',
  },
  blog: { heroEye: 'Perspectives & Actualités', heroTitle: 'Blog', heroSub: 'Articles, actualités et contenus techniques sur la manutention de charges, la logistique lourde et les meilleures pratiques opérationnelles.', featured: 'À la une', readMore: "Lire l'article complet", readMoreShort: 'Lire plus', ctaEye: 'Restez informé', ctaTitle: 'Contenu technique pour des décisions plus intelligentes', ctaSub: 'Suivez les actualités sur la manutention lourde, la sécurité opérationnelle et la logistique industrielle.', ctaBtn: 'Parler à un spécialiste' },
  frota: {
    heroEyebrow: 'Location de Matériel', heroSub: 'Flotte propre avec maintenance préventive, opérateurs certifiés et support 24/7. Vérifiez la disponibilité et demandez une location.', heroCrumb: 'Notre Flotte',
    cta: 'Demander une Location', filterMetaSingle: 'équipement disponible à la location', filterMetaPlural: 'équipements disponibles à la location',
    categories: { all: 'Tous', guindastes: 'Grues', munck: 'Camions-Grues', empilhadeiras: 'Chariots Élévateurs', 'linha-amarela': 'Ligne Jaune', plataforma: 'Nacelles', especiais: 'Charges Spéciales' },
    specLabels: { 'Capacidade': 'Capacité', 'Pluma': 'Flèche', 'Rotação': 'Rotation', 'Alcance': 'Portée', 'Acionam.': 'Actionnement', 'Balde': 'Godet', 'Prof. max': 'Prof. max', 'Tração': 'Traction', 'Peso op.': 'Poids op.', 'Profundid.': 'Profondeur', 'Alt. trab.': 'Haut. travail', 'Comprimento': 'Longueur', 'Licença': 'Permis', 'Elevação': 'Élévation', 'Plataf.': 'Plateforme', 'Eixos': 'Essieux' },
    itemNames: { 1: 'Grue Mobile Télescopique', 2: 'Grue à Flèche Treillis', 3: 'Grue Mobile Télescopique', 5: 'Camion-Grue', 6: 'Camion-Grue', 7: 'Pelleteuse Hydraulique', 8: 'Chargeuse sur Pneus', 9: 'Nacelle Articulée', 10: 'Nacelle Ciseaux', 11: 'Remorque Plateau', 12: 'Remorque Extensible', 13: 'Remorque Caisse Sider', 14: 'Remorque Caisse', 15: 'Remorque Surbaissée', 16: "Ligne d'Essieux", 17: 'Chariot Élévateur Électrique', 18: 'Chariot Élévateur Diesel' },
  },
  footer: { desc: 'Référence nationale en manutention de charges complexes, transport lourd et ingénierie de gréage avec plus de 25 ans de marché.', address: 'Siège — Duque de Caxias, RJ', navTitle: 'Navigation', navLinks: ['Accueil', "L'Entreprise", 'Nos Services', 'Notre Flotte', 'ESG', 'Certifications', 'Travailler Avec Nous'], svcTitle: 'Services', svcLinks: ['Manut. Horiz. & Vert.', 'Déplacement de Charges', 'Location de Matériel', 'Ligne Jaune', 'Transport Spécial'], contactTitle: 'Contact', reportLink: 'Canal de Signalement', contactLink: 'Nous contacter', copyright: 'Tous droits réservés.' },
  toast: { title: 'Message envoyé avec succès', subtitle: 'Nous répondrons dans un délai de 2 heures ouvrables.' },
  trabalhe: { heroEyebrow: "Rejoignez l'équipe", heroSub: "Faites partie d'un groupe avec plus de 25 ans à faire bouger le Brésil. Envoyez votre CV et attendez notre contact.", heroCrumb: 'Travailler Avec Nous' },
  contato: { heroEyebrow: 'Nous contacter', heroSub: 'Notre équipe commerciale répond avec une proposition technique dans les 2 heures ouvrables.', heroCrumb: 'Contact' },
}

// ─── Export ───────────────────────────────────────────────────────────────────
export const LANGS = { 'pt-BR': PT, 'en': EN, 'es': ES, 'de': DE, 'fr': FR }

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('pt-BR')
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: LANGS[lang] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}
